# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-09 13:35
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/', verbose_name='foodphoto')),
                ('prep_time', models.TimeField()),
                ('cooking_time', models.TimeField()),
                ('servings', models.CharField(max_length=2)),
                ('ingridients', models.CharField(max_length=100)),
                ('cooking_instaructions', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
